// @ts-check

import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

// Keep both `node:*` and bare names externalized because dependencies may import either form.
const builtins = Array.from(new Set([...builtinModules, ...builtinModules.map((name) => name.replace(/^node:/, ""))]));
const isCI = !!process.env.CI;
console.log(`Building for ${isCI ? "CI" : "local"} environment...`);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Keep vault deployment separate from bundling so esbuild has no filesystem-copy plugin dependency.
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
    ],
	format: "cjs",
	target: "esnext",
	logLevel: "info",
	minify: prod,
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
