// @ts-check

import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { obsidianCopyPlugin } from "@22-2/esbuild-plugin-obsidian-copy";

process.loadEnvFile();
// Keep both `node:*` and bare names externalized because dependencies may import either form.
const builtins = Array.from(new Set([...builtinModules, ...builtinModules.map((name) => name.replace(/^node:/, ""))]));
const pluginsPath = process.env.PLUGINS_PATH;
const isCI = !!process.env.CI;
const plugins = [];
console.log(`Building for ${isCI ? "CI" : "local"} environment...`);
if (!isCI && pluginsPath) {
	plugins.push(
		obsidianCopyPlugin({
			pluginsDir: pluginsPath,
			targetDirName: "on-demand-plugins",
			force: true,
		}),
	);
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
    ],
	format: "cjs",
	target: "esnext",
	logLevel: "info",
	minify: prod,
	plugins,
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
