// @ts-check

import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { obsidianCopyPlugin } from "@22-2/esbuild-plugin-obsidian-copy";
import dotenv from "dotenv";

dotenv.config();

const pluginsPath = process.env.PLUGINS_PATH;
const isCI = !!process.env.CI;

const plugins = [];
if (!isCI && pluginsPath) {
	plugins.push(
		obsidianCopyPlugin({
			pluginsDir: pluginsPath,
			targetDirName: "obsidian-on-demand-plugins",
			force: true,
		}),
	);
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
],
	format: "cjs",
	target: "esnext",
	logLevel: "info",
	minify: prod,
	plugins,
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
